from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    Boolean,
    DateTime,
    ForeignKey,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database.database import Base


class Notification(Base):
    __tablename__ = "notifications"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
        index=True,
    )

    type = Column(
        String(50),
        nullable=False,
    )

    title = Column(
        String(255),
        nullable=False,
    )

    message = Column(
        Text,
        nullable=False,
    )

    source_type = Column(
        String(50),
        nullable=False,
    )

    source_id = Column(
        Integer,
        nullable=False,
    )

    # ------------------------------------------------------
    # PHASE 58
    # ------------------------------------------------------
    # Stable identity for a notification event.
    #
    # This allows the same resource to generate multiple
    # meaningful notifications when its response posture
    # changes over time.
    #
    # Example:
    #
    # risk:3:continuous_response:ESCALATE:CRITICAL
    #
    # Existing notifications use a deterministic legacy
    # event key generated by the notification service.
    # ------------------------------------------------------

    event_key = Column(
        String(255),
        nullable=False,
        index=True,
    )

    is_read = Column(
        Boolean,
        default=False,
        nullable=False,
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    user = relationship(
        "User",
        back_populates="notifications",
    )

    __table_args__ = (
        UniqueConstraint(
            "user_id",
            "event_key",
            name="uq_notification_user_event_key",
        ),
    )