from pathlib import Path
import shutil
from uuid import uuid4

from fastapi import (
    APIRouter,
    Depends,
    File,
    Form,
    HTTPException,
    UploadFile,
)
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from app.auth.access import ensure_user_in_scope
from app.auth.permissions import require_permission
from app.auth.visibility import get_visible_user_ids
from app.core.config import (
    ALLOWED_UPLOAD_CONTENT_TYPES,
    ALLOWED_UPLOAD_EXTENSIONS,
    MAX_UPLOAD_SIZE_BYTES,
)
from app.database.database import get_db
from app.models.control import Control
from app.models.evidence import Evidence
from app.models.user import User
from app.schemas.evidence import (
    EvidenceCreate,
    EvidenceResponse,
    EvidenceUpdate,
)
from app.services.evidence_service import (
    create_evidence,
    delete_evidence,
    update_evidence,
)


UPLOAD_DIR = Path("uploads")
UPLOAD_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


router = APIRouter(
    prefix="/evidence",
    tags=["Evidence Management"],
)


def _validate_upload_metadata(
    file: UploadFile,
) -> str:
    """
    Validate the user-supplied upload metadata.

    The physical filename is generated by the server and
    therefore never depends on the original filename.
    """

    original_filename = (
        Path(file.filename or "")
        .name
        .strip()
    )

    if not original_filename:
        raise HTTPException(
            status_code=400,
            detail="A valid file name is required.",
        )

    if (
        original_filename in {".", ".."}
        or ".." in original_filename
    ):
        raise HTTPException(
            status_code=400,
            detail="Invalid file name.",
        )

    extension = (
        Path(original_filename)
        .suffix
        .lower()
    )

    if extension not in ALLOWED_UPLOAD_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail="File type is not allowed.",
        )

    content_type = (
        file.content_type or ""
    ).lower()

    if content_type not in ALLOWED_UPLOAD_CONTENT_TYPES:
        raise HTTPException(
            status_code=400,
            detail="File content type is not allowed.",
        )

    return original_filename


def _build_storage_path(
    original_filename: str,
) -> Path:
    """
    Generate a non-user-controlled physical filename.
    """

    extension = (
        Path(original_filename)
        .suffix
        .lower()
    )

    generated_name = (
        f"{uuid4().hex}{extension}"
    )

    return UPLOAD_DIR / generated_name


def _save_upload(
    file: UploadFile,
    destination: Path,
) -> int:
    """
    Stream the uploaded file to disk while enforcing
    the configured maximum size.

    Returns the number of bytes written.
    """

    total_bytes = 0

    try:
        with destination.open("wb") as buffer:

            while True:
                chunk = file.file.read(
                    1024 * 1024
                )

                if not chunk:
                    break

                total_bytes += len(chunk)

                if (
                    total_bytes
                    > MAX_UPLOAD_SIZE_BYTES
                ):
                    raise HTTPException(
                        status_code=413,
                        detail=(
                            "Uploaded file exceeds "
                            "the maximum allowed size."
                        ),
                    )

                buffer.write(chunk)

    except HTTPException:
        if destination.exists():
            destination.unlink()

        raise

    except Exception:
        if destination.exists():
            destination.unlink()

        raise HTTPException(
            status_code=400,
            detail="Unable to store uploaded file.",
        )

    return total_bytes


@router.post(
    "/",
    response_model=EvidenceResponse,
)
def create_new_evidence(
    control_id: int = Form(...),
    title: str = Form(...),
    description: str = Form(...),
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_permission(
            "evidence",
            "create",
        )
    ),
):
    """
    Upload evidence for a control.

    Uploaded files are stored using server-generated names
    and can only be retrieved through the authorized
    evidence download endpoint.
    """

    control = (
        db.query(Control)
        .filter(
            Control.id == control_id
        )
        .first()
    )

    if control is None:
        raise HTTPException(
            status_code=404,
            detail="Control not found.",
        )

    ensure_user_in_scope(
        db,
        current_user,
        control.owner_id,
        "evidence",
    )

    original_filename = (
        _validate_upload_metadata(file)
    )

    destination = _build_storage_path(
        original_filename
    )

    _save_upload(
        file,
        destination,
    )

    relative_file_path = str(
        destination.as_posix()
    )

    evidence_data = EvidenceCreate(
        control_id=control_id,
        title=title,
        description=description,
        file_name=original_filename,
        file_path=relative_file_path,
    )

    try:
        evidence = create_evidence(
            db,
            evidence_data,
            current_user.id,
        )

    except Exception:
        if destination.exists():
            destination.unlink()

        raise

    if evidence is None:
        if destination.exists():
            destination.unlink()

        raise HTTPException(
            status_code=404,
            detail="Unable to create evidence.",
        )

    return evidence


@router.get(
    "/",
    response_model=list[EvidenceResponse],
)
def list_all_evidence(
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_permission(
            "evidence",
            "view",
        )
    ),
):
    visible_user_ids = get_visible_user_ids(
        db,
        current_user,
        "evidence",
    )

    return (
        db.query(Evidence)
        .join(
            Control,
            Evidence.control_id
            == Control.id,
        )
        .filter(
            Control.owner_id.in_(
                visible_user_ids
            )
        )
        .all()
    )


@router.get(
    "/{evidence_id}",
    response_model=EvidenceResponse,
)
def get_evidence(
    evidence_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_permission(
            "evidence",
            "view",
        )
    ),
):
    visible_user_ids = get_visible_user_ids(
        db,
        current_user,
        "evidence",
    )

    evidence = (
        db.query(Evidence)
        .join(
            Control,
            Evidence.control_id
            == Control.id,
        )
        .filter(
            Evidence.id == evidence_id,
            Control.owner_id.in_(
                visible_user_ids
            ),
        )
        .first()
    )

    if evidence is None:
        raise HTTPException(
            status_code=404,
            detail="Evidence not found.",
        )

    return evidence


@router.get(
    "/{evidence_id}/file",
)
def download_evidence_file(
    evidence_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_permission(
            "evidence",
            "view",
        )
    ),
):
    """
    Securely retrieve an evidence file.

    The file is returned only after the evidence resource
    itself has passed the user's visibility check.
    """

    visible_user_ids = get_visible_user_ids(
        db,
        current_user,
        "evidence",
    )

    evidence = (
        db.query(Evidence)
        .join(
            Control,
            Evidence.control_id
            == Control.id,
        )
        .filter(
            Evidence.id == evidence_id,
            Control.owner_id.in_(
                visible_user_ids
            ),
        )
        .first()
    )

    if evidence is None:
        raise HTTPException(
            status_code=404,
            detail="Evidence not found.",
        )

    file_path = Path(
        evidence.file_path
    )

    if not file_path.is_absolute():
        file_path = Path.cwd() / file_path

    upload_root = (
        UPLOAD_DIR.resolve()
    )

    try:
        resolved_path = (
            file_path.resolve()
        )

        resolved_path.relative_to(
            upload_root
        )

    except ValueError:
        raise HTTPException(
            status_code=404,
            detail="Evidence file not found.",
        )

    if not resolved_path.is_file():
        raise HTTPException(
            status_code=404,
            detail="Evidence file not found.",
        )

    return FileResponse(
        path=resolved_path,
        filename=evidence.file_name,
        media_type="application/octet-stream",
        content_disposition_type="attachment",
        headers={
            "X-Content-Type-Options": "nosniff",
            "Cache-Control": (
                "private, no-store"
            ),
        },
    )


@router.patch(
    "/{evidence_id}",
    response_model=EvidenceResponse,
)
def update_existing_evidence(
    evidence_id: int,
    evidence_data: EvidenceUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_permission(
            "evidence",
            "update",
        )
    ),
):
    visible_user_ids = get_visible_user_ids(
        db,
        current_user,
        "evidence",
    )

    evidence = (
        db.query(Evidence)
        .join(
            Control,
            Evidence.control_id
            == Control.id,
        )
        .filter(
            Evidence.id == evidence_id,
            Control.owner_id.in_(
                visible_user_ids
            ),
        )
        .first()
    )

    if evidence is None:
        raise HTTPException(
            status_code=404,
            detail="Evidence not found.",
        )

    # Do not allow an API client to change the
    # server-managed physical path.
    update_data = evidence_data.model_dump(
        exclude_unset=True
    )

    if "file_path" in update_data:
        raise HTTPException(
            status_code=400,
            detail=(
                "Evidence file path cannot "
                "be changed directly."
            ),
        )

    updated_evidence = update_evidence(
        db,
        evidence_id,
        evidence_data,
    )

    if updated_evidence is None:
        raise HTTPException(
            status_code=404,
            detail="Evidence not found.",
        )

    return updated_evidence


@router.delete(
    "/{evidence_id}",
)
def delete_existing_evidence(
    evidence_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_permission(
            "evidence",
            "delete",
        )
    ),
):
    visible_user_ids = get_visible_user_ids(
        db,
        current_user,
        "evidence",
    )

    evidence = (
        db.query(Evidence)
        .join(
            Control,
            Evidence.control_id
            == Control.id,
        )
        .filter(
            Evidence.id == evidence_id,
            Control.owner_id.in_(
                visible_user_ids
            ),
        )
        .first()
    )

    if evidence is None:
        raise HTTPException(
            status_code=404,
            detail="Evidence not found.",
        )

    physical_path = Path(
        evidence.file_path
    )

    if not physical_path.is_absolute():
        physical_path = (
            Path.cwd() / physical_path
        )

    deleted = delete_evidence(
        db,
        evidence_id,
    )

    if deleted is None:
        raise HTTPException(
            status_code=404,
            detail="Evidence not found.",
        )

    try:
        resolved_path = (
            physical_path.resolve()
        )
        upload_root = (
            UPLOAD_DIR.resolve()
        )

        resolved_path.relative_to(
            upload_root
        )

        if resolved_path.is_file():
            resolved_path.unlink()

    except (ValueError, OSError):
        # Database deletion has already succeeded.
        # Never expose filesystem details to the client.
        pass

    return {
        "message": (
            "Evidence deleted successfully."
        ),
    }