import {
  Bot,
  ShieldAlert,
  CheckCircle2,
  ArrowRightCircle,
} from "lucide-react";

interface Props {
  riskLevel: string;
  summary: string;
  priorities: string[];
  nextSteps: string[];
}

export default function AISummary({
  riskLevel,
  summary,
  priorities,
  nextSteps,
}: Props) {

  const badgeColor = () => {
    switch (riskLevel.toLowerCase()) {
      case "low":
        return "bg-emerald-100 text-emerald-700";

      case "medium":
        return "bg-amber-100 text-amber-700";

      case "high":
        return "bg-orange-100 text-orange-700";

      case "critical":
        return "bg-red-100 text-red-700";

      default:
        return "bg-slate-100 text-slate-700";
    }
  };

  return (
    <div className="rounded-2xl border border-slate-200 bg-white shadow-sm">

      {/* Header */}

      <div className="flex items-center gap-3 border-b border-slate-200 p-6">

        <div className="rounded-xl bg-blue-600 p-3 text-white">

          <Bot size={24} />

        </div>

        <div>

          <h2 className="text-xl font-bold">
            AI Executive Summary
          </h2>

          <p className="text-sm text-slate-500">
            Generated by CyberGRC AI
          </p>

        </div>

      </div>

      {/* Body */}

      <div className="space-y-6 p-6">

        {/* Risk Level */}

        <div>

          <p className="mb-2 text-sm font-medium text-slate-500">
            Overall Risk Level
          </p>

          <span
            className={`inline-flex rounded-full px-4 py-2 text-sm font-semibold ${badgeColor()}`}
          >
            {riskLevel}
          </span>

        </div>

        {/* Executive Summary */}

        <div>

          <h3 className="mb-3 flex items-center gap-2 font-semibold">

            <ShieldAlert size={18} />

            Executive Summary

          </h3>

          <p className="leading-7 text-slate-600">
            {summary}
          </p>

        </div>

        {/* Priorities */}

        <div>

          <h3 className="mb-3 flex items-center gap-2 font-semibold">

            <CheckCircle2
              size={18}
              className="text-red-500"
            />

            Top Priorities

          </h3>

          <ul className="space-y-2">

            {priorities.map((item) => (

              <li
                key={item}
                className="flex items-center gap-2"
              >

                <span className="text-red-500">
                  ✓
                </span>

                {item}

              </li>

            ))}

          </ul>

        </div>

        {/* Next Steps */}

        <div>

          <h3 className="mb-3 flex items-center gap-2 font-semibold">

            <ArrowRightCircle
              size={18}
              className="text-blue-600"
            />

            Recommended Next Steps

          </h3>

          <ul className="space-y-2">

            {nextSteps.map((item) => (

              <li
                key={item}
                className="flex items-center gap-2"
              >

                <span className="text-blue-600">
                  →
                </span>

                {item}

              </li>

            ))}

          </ul>

        </div>

      </div>

    </div>
  );
}