import { Bot } from "lucide-react";

interface Props {
  riskLevel: string;
  summary: string;
  priorities: string[];
  nextSteps: string[];
}

export default function AISummary({
  riskLevel,
  summary,
  priorities,
  nextSteps,
}: Props) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">

      <div className="mb-6 flex items-center gap-3">

        <div className="rounded-xl bg-blue-600 p-3 text-white">
          <Bot size={24} />
        </div>

        <div>
          <h2 className="text-xl font-bold">
            AI Executive Summary
          </h2>

          <p className="text-sm text-slate-500">
            Generated by CyberGRC AI
          </p>
        </div>

      </div>

      <div className="space-y-6">

        <div>
          <p className="text-sm text-slate-500">
            Overall Risk Level
          </p>

          <span className="mt-2 inline-flex rounded-full bg-amber-100 px-4 py-2 text-sm font-semibold text-amber-700">
            {riskLevel}
          </span>
        </div>

        <p className="leading-7 text-slate-700">
          {summary}
        </p>

        <div>

          <h3 className="mb-3 font-semibold">
            Top Priorities
          </h3>

          <ul className="space-y-2">

            {priorities.map((item) => (
              <li key={item}>
                • {item}
              </li>
            ))}

          </ul>

        </div>

        <div>

          <h3 className="mb-3 font-semibold">
            Recommended Next Steps
          </h3>

          <ul className="space-y-2">

            {nextSteps.map((item) => (
              <li key={item}>
                • {item}
              </li>
            ))}

          </ul>

        </div>

      </div>

    </div>
  );
}