"""Add framework control model

Revision ID: eec567b2fb46
Revises: b41b6c1f2fb1
Create Date: 2026-08-04 15:39:25.112384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec567b2fb46'
down_revision: Union[str, Sequence[str], None] = 'b41b6c1f2fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('framework_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('control_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_framework_controls_id'), 'framework_controls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_framework_controls_id'), table_name='framework_controls')
    op.drop_table('framework_controls')
    # ### end Alembic commands ###
